spring.application.name=account-service
server.port=8040
spring.devtools.restart.enabled=true

# EUREKA CONFIGURATION
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.service-url.defaultZone=http://localhost:8010/eureka

spring.config.import=optional:configserver:http://localhost:8020
spring.cloud.config.enabled=true